### ISSUE TITLE
MG+MIS Evaluation

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#14]
The MG+MIS documents are ready for evaluation.

[MG.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/Design/SoftArchitecture/MG.pdf)

[MIS.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by smiths** [comment]
[MortezaMG.pdf - PDF Expert.pdf](https://github.com/mirzaim/ipcs/files/14846183/MortezaMG.pdf.-.PDF.Expert.pdf)
[MortezaMIS.pdf - PDF Expert.pdf](https://github.com/mirzaim/ipcs/files/14846185/MortezaMIS.pdf.-.PDF.Expert.pdf)
