### ISSUE TITLE
MG+MIS Evaluation For Secondary Reviewer

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#16]
The MG+MIS documents are ready for evaluation.

[MG.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/Design/SoftArchitecture/MG.pdf)

[MIS.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by adrian-soch** [comment]
Hi @mirzaim, good job, the design documents are well done, and easy to read/understand. I have added my review, mostly small cosmetic issues.
