### ISSUE TITLE
SRS Evaluation

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#3]
The SRS is ready for evaluation.

[SRS.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/SRS/SRS.pdf)

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[MortezaMirzaei_SRS.pdf](https://github.com/mirzaim/ipcs/files/14390014/MortezaMirzaei_SRS.pdf)
