### ISSUE TITLE
SRS Evaluation For Domain Expert

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#4]
The SRS is ready for evaluation.

[SRS.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/SRS/SRS.pdf)

**Comment by smiths** [comment]
@alimousavi1997 your review still hasn't been completed.

**Comment by alimousavi1997** [comment]
[SRS_review_mirzaie.pdf](https://github.com/mirzaim/ipcs/files/14394190/SRS_review_mirzaie.pdf)
Your SRS review
