### ISSUE TITLE
SRS Evaluation for Secondary Reviewer

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#5]
The SRS is ready for evaluation.

[SRS.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/SRS/SRS.pdf)

**Comment by smiths** [comment]
@XessX please complete the review for the SRS.

**Comment by XessX** [comment]
I have reviewed your SRS and created the following issue:
#13 
Thanks.
